version: "3.8"

services:
  wedding_db:
    image: postgres:10
    container_name: wedding_db
    environment:
      - POSTGRES_DB=wedding_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
    volumes:
      - .:/app
  
  
  app:
    build: .
    container_name: wedding_db
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - postgres_db
    ports:
      - "8000:8000"
    env_file:
      - .env