# Generated by Django 4.0.6 on 2022-07-13 12:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='EvantModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='files/')),
                ('name', models.CharField(max_length=30)),
                ('active', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='MenuModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=30)),
                ('price', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='SystemInfoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('type', models.CharField(max_length=40)),
                ('description', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SystemInfoFileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, upload_to='systeminfo/')),
                ('systeminfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.systeminfomodel')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('type', models.CharField(max_length=30)),
                ('price', models.PositiveIntegerField(default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='service/')),
                ('file', models.FileField(blank=True, null=True, upload_to='service/')),
                ('description', models.TextField(blank=True, null=True)),
                ('category_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.category')),
                ('event_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.evantmodel')),
            ],
        ),
        migrations.CreateModel(
            name='RestoranModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restoran', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='restoran/')),
                ('file', models.FileField(blank=True, null=True, upload_to='restoran/')),
                ('event_id', models.ManyToManyField(related_name='restorans', to='services.evantmodel')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(blank=True)),
                ('gests_amount', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(blank=True, choices=[('In process', 'In process'), ('Completed', 'Completed'), ('Canceled', 'Canceled')], default='In process', max_length=15)),
                ('total_price', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.menumodel')),
                ('restoran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.restoranmodel')),
                ('service', models.ManyToManyField(blank=True, to='services.servicemodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='menumodel',
            name='restoran_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menus', to='services.restoranmodel'),
        ),
        migrations.CreateModel(
            name='MenuItemModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='menuitems/')),
                ('itam_name', models.CharField(max_length=30)),
                ('menu_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menuitems', to='services.menumodel')),
            ],
        ),
        migrations.CreateModel(
            name='BookedDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('booked_dates', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booked_dates', to='services.restoranmodel')),
            ],
            options={
                'unique_together': {('date', 'booked_dates')},
            },
        ),
    ]
