# Generated by Django 4.0.6 on 2022-07-17 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_rename_menu_menumodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restoranmodel',
            name='file',
        ),
        migrations.RemoveField(
            model_name='systeminfomodel',
            name='type',
        ),
    ]
